apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: campaign-cronjob-role
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["create", "get", "list", "watch", "delete"]

