apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: campaign-cronjob-rolebinding
subjects:
- kind: ServiceAccount
  name: default  # The default service account
  namespace: default
roleRef:
  kind: Role
  name: campaign-cronjob-role
  apiGroup: rbac.authorization.k8s.io

