apiVersion: v1
kind: PersistentVolume
metadata:
  name: twitter-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/twitter"  # Local storage on the Kubernetes node (for testing)

